// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zqjrvbqleqrgblygmteq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxanJ2YnFsZXFyZ2JseWdtdGVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMDc3NzAsImV4cCI6MjA3NTc4Mzc3MH0.bkD3wr6QrgFAoi6xXIilwd0ezH0OIU-nbCFrlB8NK6I";

// Import the supabase client like this:
// import { supabase } from "@/src/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);